services:
- type: web
  name: ghost
  env: docker
  healthCheckPath: /
  envVars:
  - key: url
    value: https://ghost342.onrender.com
  disk:
    name: ghost-content
    mountPath: /var/lib/ghost/content
    sizeGB: 10
